# _config.yml
title: My Jekyll Site
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my Jekyll site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
